<?php

// Controllers

\z\cons('EXCEPTION_CONTROLLER_NOT_FOUND');
\z\cons('EXCEPTION_CONTROLLER_NOT_INSTANTIABLE');
\z\cons('EXCEPTION_CONTROLLER_ACTION_NOT_FOUND');


// Files

\z\cons('EXCEPTION_FILE_NOT_FOUND');
\z\cons('EXCEPTION_FILE_NOT_GRANTED');


// HTTP

\z\cons('EXCEPTION_HTTP_STATUS_CODE_NOT_VALID');


// Permissions

\z\cons('EXCEPTION_PERMISSION_NOT_GRANTED');


// Preferences

\z\cons('EXCEPTION_PREFERENCE_NOT_AN_ARRAY');


// Routes

\z\cons('EXCEPTION_ROUTE_NOT_FOUND');


// Services

\z\cons('EXCEPTION_SERVICE_NOT_FOUND');
\z\cons('EXCEPTION_SERVICE_NOT_INSTANTIABLE');


// Variables

\z\cons('EXCEPTION_VARIABLE_NOT_FOUND');
\z\cons('EXCEPTION_VARIABLE_PATH_NOT_VALID');

?>
